# Generated by Django 5.0.3 on 2024-04-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=250)),
                ('model_name', models.CharField(max_length=250)),
                ('sim_type', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
            ],
        ),
    ]
