# Generated by Django 5.0.3 on 2024-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproduct',
            name='price',
            field=models.IntegerField(default=25000),
        ),
    ]
