# Generated by Django 5.0.3 on 2024-04-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='status1',
            new_name='status2',
        ),
    ]
