# Generated by Django 5.0.3 on 2024-05-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='date',
            new_name='expiry_date',
        ),
    ]
