# Generated by Django 5.0.3 on 2024-05-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
