# Generated by Django 5.0.3 on 2024-05-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileproduct',
            name='company',
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='price',
            field=models.CharField(max_length=250),
        ),
    ]
