# Generated by Django 5.0.3 on 2024-04-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_mobile_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobile_product',
            new_name='mobileproduct',
        ),
    ]
