# Generated by Django 5.0.3 on 2024-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_rename_date_pay_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
