# Generated by Django 5.0.3 on 2024-05-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_remove_mobileproduct_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileproduct',
            old_name='user',
            new_name='seller',
        ),
    ]
