# Generated by Django 5.0.3 on 2024-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_customer_profile_picture_seller_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
