# Generated by Django 5.0.3 on 2024-05-30 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_alter_customer_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobileproduct',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
