# Generated by Django 5.0.3 on 2024-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_rename_mobileproduct_product_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
