# Generated by Django 5.0.3 on 2024-05-07 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_alter_mobileproduct_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales_app.seller'),
        ),
    ]
