# Generated by Django 5.0.3 on 2024-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0010_alter_cart_customer_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
